FROM python:3.13-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir 'litellm[proxy]'
EXPOSE 4000
ENTRYPOINT [ \
  "litellm", \
  "--config", "/litellm-config.yaml", \
  "--host", "0.0.0.0", \
  "--port", "4000" \
]